version: "3"

services:
  postgres:
    image: "postgres:16"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    image: golang:1.21.5-alpine
    volumes:
      - ./:/server_app
    working_dir: /server_app
    command: sh -c "go install github.com/mitranim/gow@latest && gow run ./cmd/main.go"
    ports:
      - "1234:1234"
    depends_on:
      - postgres
volumes:
  postgres: